import fs from 'fs';
import path from 'path';

const filePath = path.resolve('frontend/src/pages/RoadmapsPage.jsx');
let content = fs.readFileSync(filePath, 'utf8');

// 1. Ensure import of TopicSubtopicsView
if (!content.includes('TopicSubtopicsView')) {
  content = content.replace(
    "import { CuratedSheetsView } from '../components/CuratedSheetsView';",
    "import { CuratedSheetsView } from '../components/CuratedSheetsView';\nimport { TopicSubtopicsView } from '../components/TopicSubtopicsView';"
  );
}

// 2. Prepare full catalog entries for the missing and new topics
const additionalCatalogs = `
  'two-pointers': {
    title: 'Two Pointers & Binary Invariants Ladder',
    desc: 'Core Invariant: Converging or parallel index bounds exploiting sorted arrays or monotonic properties.',
    elo: '1,720 Elo • 91% AC',
    progress: '2 / 4 Mastered',
    steps: [
      {
        level: 'Level 1: Opposing Convergence',
        badgeColor: 'text-white',
        dotColor: 'bg-white',
        borderClass: 'border-white/30',
        name: 'Valid Palindrome',
        diff: 'Easy',
        diffClass: 'bg-white/10 text-white border border-white/20',
        lc: 'LC #125',
        intuition: 'Symmetric inward movement. Filter alphanumeric characters and verify equality while left < right.',
        status: 'Mastered',
        statusColor: 'text-white',
        actionText: 'Review Notes ->',
      },
      {
        level: 'Level 2: Sorted Sum Bounds',
        badgeColor: 'text-[#FF7A00]',
        dotColor: 'bg-[#FF7A00]',
        borderClass: 'border-[#FF7A00]/50',
        name: 'Two Sum II - Input Array Is Sorted',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #167',
        intuition: 'Monotonic sum invariant: sum < target increment left; sum > target decrement right.',
        status: 'Ready to Solve',
        statusColor: 'text-[#FF7A00] font-bold',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 3: Fixed Anchor + Pointers',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D]',
        name: '3Sum',
        diff: 'Medium',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #15',
        intuition: 'Sort array, fix first element i, run two-pointer convergence on remaining subarray with duplicate skipping.',
        status: 'Ready to Solve',
        statusColor: 'text-[#8B949E]',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 4: Dynamic Capacity Envelope',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D] opacity-60',
        name: 'Trapping Rain Water',
        diff: 'Hard',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #42',
        intuition: 'Dual tracking of leftMax and rightMax; the smaller height bottleneck strictly dictates trapped volume.',
        status: 'Prerequisite Required',
        statusColor: 'text-[#8B949E]',
        actionText: 'Locked Barrier',
      },
    ],
  },
  'prefix-sum': {
    title: 'Prefix Sum & Difference Array Ladder',
    desc: 'Core Invariant: Precomputed cumulative sums enabling O(1) range sum queries and O(1) interval updates.',
    elo: '1,680 Elo • 89% AC',
    progress: '2 / 4 Mastered',
    steps: [
      {
        level: 'Level 1: Cumulative Offset',
        badgeColor: 'text-white',
        dotColor: 'bg-white',
        borderClass: 'border-white/30',
        name: 'Running Sum of 1d Array',
        diff: 'Easy',
        diffClass: 'bg-white/10 text-white border border-white/20',
        lc: 'LC #1480',
        intuition: 'In-place cumulative accumulation nums[i] += nums[i-1].',
        status: 'Mastered',
        statusColor: 'text-white',
        actionText: 'Review Notes ->',
      },
      {
        level: 'Level 2: Target Delta Hash Map',
        badgeColor: 'text-[#FF7A00]',
        dotColor: 'bg-[#FF7A00]',
        borderClass: 'border-[#FF7A00]/50',
        name: 'Subarray Sum Equals K',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #560',
        intuition: 'Prefix sum hash map: count occurrences of (currSum - k) seen prior to index i.',
        status: 'Ready to Solve',
        statusColor: 'text-[#FF7A00] font-bold',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 3: Modular Congruence',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D]',
        name: 'Continuous Subarray Sum',
        diff: 'Medium',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #523',
        intuition: 'Prefix sum modulo k: identical remainder at indices i and j implies subarray sum between them is multiple of k.',
        status: 'Ready to Solve',
        statusColor: 'text-[#8B949E]',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 4: 2D Integral Matrix',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D] opacity-60',
        name: 'Range Sum Query 2D - Immutable',
        diff: 'Medium',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #304',
        intuition: 'Inclusion-exclusion principle: dp[r2][c2] - dp[r1-1][c2] - dp[r2][c1-1] + dp[r1-1][c1-1].',
        status: 'Ready to Solve',
        statusColor: 'text-[#8B949E]',
        actionText: 'Solve Problem ->',
      },
    ],
  },
  'linked-list': {
    title: 'Linked List Structural Pointer Ladder',
    desc: 'Core Invariant: Sequential memory traversal, slow-fast cycle detection, dummy head nodes, and pointer manipulation.',
    elo: '1,650 Elo • 92% AC',
    progress: '2 / 4 Mastered',
    steps: [
      {
        level: 'Level 1: Directional Inversion',
        badgeColor: 'text-white',
        dotColor: 'bg-white',
        borderClass: 'border-white/30',
        name: 'Reverse Linked List',
        diff: 'Easy',
        diffClass: 'bg-white/10 text-white border border-white/20',
        lc: 'LC #206',
        intuition: 'Iterative 3-pointer rewind (prev, curr, nextTemp) in-place without memory allocation.',
        status: 'Mastered',
        statusColor: 'text-white',
        actionText: 'Review Notes ->',
      },
      {
        level: 'Level 2: Fast & Slow Cycle',
        badgeColor: 'text-[#FF7A00]',
        dotColor: 'bg-[#FF7A00]',
        borderClass: 'border-[#FF7A00]/50',
        name: 'Linked List Cycle II',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #142',
        intuition: 'Floyd cycle finding: 2x speed meeting point; resetting one pointer to head lands both at cycle entry.',
        status: 'Ready to Solve',
        statusColor: 'text-[#FF7A00] font-bold',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 3: Interleaving Midpoint',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D]',
        name: 'Reorder List',
        diff: 'Medium',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #143',
        intuition: 'Find midpoint via slow-fast, reverse second half in-place, and interleave nodes alternately.',
        status: 'Ready to Solve',
        statusColor: 'text-[#8B949E]',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 4: K-Way Heap Reduction',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D] opacity-60',
        name: 'Merge k Sorted Lists',
        diff: 'Hard',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #23',
        intuition: 'Min-heap of k node heads or divide-and-conquer pairwise merge in O(N log k) total time.',
        status: 'Prerequisite Required',
        statusColor: 'text-[#8B949E]',
        actionText: 'Locked Barrier',
      },
    ],
  },
  'bit-manipulation': {
    title: 'Bit Manipulation Invariant Ladder',
    desc: 'Core Invariant: Low-level bitwise masking, XOR cancellation (x ^ x = 0), and 2s-complement lowbit extraction.',
    elo: '1,810 Elo • 84% AC',
    progress: '2 / 4 Mastered',
    steps: [
      {
        level: 'Level 1: XOR Parity Cancellation',
        badgeColor: 'text-white',
        dotColor: 'bg-white',
        borderClass: 'border-white/30',
        name: 'Single Number',
        diff: 'Easy',
        diffClass: 'bg-white/10 text-white border border-white/20',
        lc: 'LC #136',
        intuition: 'XOR all elements: duplicate pairs cancel to zero, leaving the unique element in O(1) space.',
        status: 'Mastered',
        statusColor: 'text-white',
        actionText: 'Review Notes ->',
      },
      {
        level: 'Level 2: Lowest Set Bit Clearing',
        badgeColor: 'text-[#FF7A00]',
        dotColor: 'bg-[#FF7A00]',
        borderClass: 'border-[#FF7A00]/50',
        name: 'Number of 1 Bits',
        diff: 'Easy',
        diffClass: 'bg-white/10 text-white border border-white/20',
        lc: 'LC #191',
        intuition: 'Brian Kernighan algorithm: n = n & (n - 1) clears lowest set bit in iterations equal to set bit count.',
        status: 'Ready to Solve',
        statusColor: 'text-[#FF7A00] font-bold',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 3: Bitmask Subset Traversal',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D]',
        name: 'Counting Bits',
        diff: 'Easy',
        diffClass: 'bg-white/10 text-white border border-white/20',
        lc: 'LC #338',
        intuition: 'DP state transition: ans[i] = ans[i >> 1] + (i & 1) in linear O(N) time.',
        status: 'Ready to Solve',
        statusColor: 'text-[#8B949E]',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 4: Bitmask State DP',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D] opacity-60',
        name: 'Subsets',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #78',
        intuition: 'Loop integer mask from 0 to 2^n - 1; test (mask & (1 << j)) to construct all power set subsets.',
        status: 'Ready to Solve',
        statusColor: 'text-[#8B949E]',
        actionText: 'Solve Problem ->',
      },
    ],
  },
  'union-find': {
    title: 'Disjoint Set Union (DSU) Invariant Ladder',
    desc: 'Core Invariant: Near O(1) amortized connected components via path compression and rank union heuristics.',
    elo: '1,890 Elo • 82% AC',
    progress: '1 / 4 Mastered',
    steps: [
      {
        level: 'Level 1: Redundant Edge Cycle',
        badgeColor: 'text-white',
        dotColor: 'bg-white',
        borderClass: 'border-white/30',
        name: 'Redundant Connection',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #684',
        intuition: 'DSU find cycle: if find(u) == find(v), adding edge (u, v) creates a cycle; return edge.',
        status: 'Mastered',
        statusColor: 'text-white',
        actionText: 'Review Notes ->',
      },
      {
        level: 'Level 2: Connected Component Count',
        badgeColor: 'text-[#FF7A00]',
        dotColor: 'bg-[#FF7A00]',
        borderClass: 'border-[#FF7A00]/50',
        name: 'Number of Provinces',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #547',
        intuition: 'Initialize N components. Each successful union decrement component count by 1.',
        status: 'Ready to Solve',
        statusColor: 'text-[#FF7A00] font-bold',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 3: Grid Coordinate Flattening',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D]',
        name: 'Surrounded Regions',
        diff: 'Medium',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #130',
        intuition: 'Virtual dummy node connected to all boundary "O" cells; interior cells not connected to dummy get captured.',
        status: 'Ready to Solve',
        statusColor: 'text-[#8B949E]',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 4: Dynamic Matrix Percolation',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D] opacity-60',
        name: 'Number of Islands II',
        diff: 'Hard',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #305',
        intuition: 'Online grid island queries: add land node, union with up to 4 neighbors, and record running count.',
        status: 'Prerequisite Required',
        statusColor: 'text-[#8B949E]',
        actionText: 'Locked Barrier',
      },
    ],
  },
  strings: {
    title: 'String Algorithms & Pattern Matching Ladder',
    desc: 'Core Invariant: Longest prefix-suffix arrays (KMP failure function), rolling hash polynomials, and palindromic centers.',
    elo: '1,780 Elo • 85% AC',
    progress: '1 / 4 Mastered',
    steps: [
      {
        level: 'Level 1: Prefix Character Invariant',
        badgeColor: 'text-white',
        dotColor: 'bg-white',
        borderClass: 'border-white/30',
        name: 'Longest Common Prefix',
        diff: 'Easy',
        diffClass: 'bg-white/10 text-white border border-white/20',
        lc: 'LC #14',
        intuition: 'Vertical scanning across character index across all strings or horizontal prefix reduction.',
        status: 'Mastered',
        statusColor: 'text-white',
        actionText: 'Review Notes ->',
      },
      {
        level: 'Level 2: KMP Prefix-Suffix Table',
        badgeColor: 'text-[#FF7A00]',
        dotColor: 'bg-[#FF7A00]',
        borderClass: 'border-[#FF7A00]/50',
        name: 'Find the Index of the First Occurrence in a String',
        diff: 'Easy',
        diffClass: 'bg-white/10 text-white border border-white/20',
        lc: 'LC #28',
        intuition: 'Knuth-Morris-Pratt failure table (LPS): eliminate backtracking upon mismatch by jumping to longest prefix suffix.',
        status: 'Ready to Solve',
        statusColor: 'text-[#FF7A00] font-bold',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 3: Palindromic Center Expansion',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D]',
        name: 'Longest Palindromic Substring',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #5',
        intuition: 'Expand outward from 2n-1 odd and even centers; update maximum diameter while mirror bounds hold.',
        status: 'Ready to Solve',
        statusColor: 'text-[#8B949E]',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 4: Dynamic Partition Decomposition',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D] opacity-60',
        name: 'Word Break II',
        diff: 'Hard',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #140',
        intuition: 'Memoized DFS with trie prefix lookups to yield all valid space-delimited string segmentations.',
        status: 'Prerequisite Required',
        statusColor: 'text-[#8B949E]',
        actionText: 'Locked Barrier',
      },
    ],
  },
  recursion: {
    title: 'Recursion & Divide-and-Conquer Ladder',
    desc: 'Core Invariant: Self-similar subproblem reduction, base-case guarantees, call stack unwinding, and expression parsing.',
    elo: '1,790 Elo • 86% AC',
    progress: '1 / 4 Mastered',
    steps: [
      {
        level: 'Level 1: Binary Exponentiation',
        badgeColor: 'text-white',
        dotColor: 'bg-white',
        borderClass: 'border-white/30',
        name: 'Pow(x, n)',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #50',
        intuition: 'Divide exponent in half: x^n = (x^2)^(n/2); reduces O(N) multiplication steps to O(log N).',
        status: 'Mastered',
        statusColor: 'text-white',
        actionText: 'Review Notes ->',
      },
      {
        level: 'Level 2: Divide-and-Conquer Sort',
        badgeColor: 'text-[#FF7A00]',
        dotColor: 'bg-[#FF7A00]',
        borderClass: 'border-[#FF7A00]/50',
        name: 'Sort an Array',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #912',
        intuition: 'Split problem domain into equal halves, solve recursively, and merge sorted arrays in linear O(N) time.',
        status: 'Ready to Solve',
        statusColor: 'text-[#FF7A00] font-bold',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 3: Recursive Grammar Unrolling',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D]',
        name: 'Flatten Nested List Iterator',
        diff: 'Medium',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #341',
        intuition: 'Recursive generator or stack of list iterators lazily unrolling nested sub-lists.',
        status: 'Ready to Solve',
        statusColor: 'text-[#8B949E]',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 4: Recursive Descent Calculator',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D] opacity-60',
        name: 'Basic Calculator',
        diff: 'Hard',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #224',
        intuition: 'Maintain sign and current term; open parenthesis pushes state onto stack; closing resolves parenthesis scope.',
        status: 'Prerequisite Required',
        statusColor: 'text-[#8B949E]',
        actionText: 'Locked Barrier',
      },
    ],
  },
  sorting: {
    title: 'Sorting Algorithms & Array Partitions Ladder',
    desc: 'Core Invariant: Dutch National Flag partitions, custom comparator transitivity, Quickselect expected O(N) selection.',
    elo: '1,740 Elo • 90% AC',
    progress: '2 / 4 Mastered',
    steps: [
      {
        level: 'Level 1: Dutch 3-Way Partition',
        badgeColor: 'text-white',
        dotColor: 'bg-white',
        borderClass: 'border-white/30',
        name: 'Sort Colors',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #75',
        intuition: 'Dutch National Flag: 3 pointers (low, mid, high) separating 0s, 1s, and 2s in a single in-place pass.',
        status: 'Mastered',
        statusColor: 'text-white',
        actionText: 'Review Notes ->',
      },
      {
        level: 'Level 2: Custom String Comparator',
        badgeColor: 'text-[#FF7A00]',
        dotColor: 'bg-[#FF7A00]',
        borderClass: 'border-[#FF7A00]/50',
        name: 'Largest Number',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #179',
        intuition: 'Sort strings using comparator (a + b) > (b + a); verify transitive ordering and edge case zeroes.',
        status: 'Ready to Solve',
        statusColor: 'text-[#FF7A00] font-bold',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 3: Quickselect Expected O(N)',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D]',
        name: 'Kth Largest Element in an Array',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #215',
        intuition: 'Partition array like quicksort; branch only into the partition containing the target rank k.',
        status: 'Ready to Solve',
        statusColor: 'text-[#8B949E]',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 4: Inversion Count Migration',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D] opacity-60',
        name: 'Count of Smaller Numbers After Self',
        diff: 'Hard',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #315',
        intuition: 'Merge sort index tracking or Fenwick tree frequency updates while iterating right-to-left.',
        status: 'Prerequisite Required',
        statusColor: 'text-[#8B949E]',
        actionText: 'Locked Barrier',
      },
    ],
  },
  'fenwick-tree': {
    title: 'Binary Indexed Tree & Segment Tree Ladder',
    desc: 'Core Invariant: Prefix range decomposition via lowest set bit (i & -i), point updates in O(log N), and lazy interval tags.',
    elo: '1,960 Elo • 72% AC',
    progress: '1 / 4 Mastered',
    steps: [
      {
        level: 'Level 1: Point Update & Prefix Query',
        badgeColor: 'text-white',
        dotColor: 'bg-white',
        borderClass: 'border-white/30',
        name: 'Range Sum Query - Mutable',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #307',
        intuition: 'Fenwick Tree using lowbit (i & -i) to propagate updates upward and query prefix sums in O(log N).',
        status: 'Mastered',
        statusColor: 'text-white',
        actionText: 'Review Notes ->',
      },
      {
        level: 'Level 2: Coordinate Compression BIT',
        badgeColor: 'text-[#FF7A00]',
        dotColor: 'bg-[#FF7A00]',
        borderClass: 'border-[#FF7A00]/50',
        name: 'Queue Reconstruction by Height',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #406',
        intuition: 'Fenwick tree binary search or segment tree to find the k-th empty slot in O(N log N) total time.',
        status: 'Ready to Solve',
        statusColor: 'text-[#FF7A00] font-bold',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 3: 2D Submatrix Range Query',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D]',
        name: 'Range Sum Query 2D - Mutable',
        diff: 'Hard',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #308',
        intuition: '2D Fenwick tree with nested lowbit loops for point updates and 2D prefix sums.',
        status: 'Ready to Solve',
        statusColor: 'text-[#8B949E]',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 4: Dynamic Segment Tree + Lazy Tags',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D] opacity-60',
        name: 'Falling Squares',
        diff: 'Hard',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #699',
        intuition: 'Segment tree with coordinate compression and lazy propagation tags for interval max height updates.',
        status: 'Prerequisite Required',
        statusColor: 'text-[#8B949E]',
        actionText: 'Locked Barrier',
      },
    ],
  },
  'sweep-line': {
    title: 'Sweep Line & Event Processing Ladder',
    desc: 'Core Invariant: Chronological event point sorting, active boundary tracking, 2D geometry projection, and interval concurrency.',
    elo: '1,920 Elo • 76% AC',
    progress: '1 / 4 Mastered',
    steps: [
      {
        level: 'Level 1: Concurrent Interval Bounds',
        badgeColor: 'text-white',
        dotColor: 'bg-white',
        borderClass: 'border-white/30',
        name: 'Meeting Rooms II',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #253',
        intuition: 'Separate start and end timestamps into sorted arrays; increment room concurrency on start, decrement on end.',
        status: 'Mastered',
        statusColor: 'text-white',
        actionText: 'Review Notes ->',
      },
      {
        level: 'Level 2: Active Multiset & Skyline Contour',
        badgeColor: 'text-[#FF7A00]',
        dotColor: 'bg-[#FF7A00]',
        borderClass: 'border-[#FF7A00]/50',
        name: 'The Skyline Problem',
        diff: 'Hard',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #218',
        intuition: 'Sweep vertical line along building edges. Multiset/max-heap of heights emits keypoint on max height transition.',
        status: 'Ready to Solve',
        statusColor: 'text-[#FF7A00] font-bold',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 3: Difference Array on Timeline',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D]',
        name: 'Car Pooling',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #1094',
        intuition: 'Bucket difference array: +passenger at pickup, -passenger at dropoff; verify cumulative load <= capacity.',
        status: 'Ready to Solve',
        statusColor: 'text-[#8B949E]',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 4: 2D Rectangle Area Union',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D] opacity-60',
        name: 'Rectangle Area II',
        diff: 'Hard',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #850',
        intuition: 'Sweep line along X-axis with active Y-intervals merged via segment tree modulo 1e9+7.',
        status: 'Prerequisite Required',
        statusColor: 'text-[#8B949E]',
        actionText: 'Locked Barrier',
      },
    ],
  },
  'monotonic-queue': {
    title: 'Monotonic Queue & Deque Ladder',
    desc: 'Core Invariant: Extremum maintenance in sliding windows, double-ended pruning of dominated candidates, and DP acceleration to O(N).',
    elo: '1,880 Elo • 81% AC',
    progress: '1 / 4 Mastered',
    steps: [
      {
        level: 'Level 1: Double-Ended Window Maxima',
        badgeColor: 'text-white',
        dotColor: 'bg-white',
        borderClass: 'border-white/30',
        name: 'Sliding Window Maximum',
        diff: 'Hard',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #239',
        intuition: 'Monotonic decreasing deque of indices: evict expired left indices and pop smaller tail items to maintain max at front.',
        status: 'Mastered',
        statusColor: 'text-white',
        actionText: 'Review Notes ->',
      },
      {
        level: 'Level 2: Dual Deque Limit Range',
        badgeColor: 'text-[#FF7A00]',
        dotColor: 'bg-[#FF7A00]',
        borderClass: 'border-[#FF7A00]/50',
        name: 'Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #1438',
        intuition: 'Two monotonic deques (one min, one max); slide left window pointer when maxDeque.front - minDeque.front > limit.',
        status: 'Ready to Solve',
        statusColor: 'text-[#FF7A00] font-bold',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 3: DP Transition Acceleration',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D]',
        name: 'Jump Game VI',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #1696',
        intuition: 'DP state dp[i] = nums[i] + max(dp[i-k..i-1]) accelerated from O(Nk) to linear O(N) using max-deque.',
        status: 'Ready to Solve',
        statusColor: 'text-[#8B949E]',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 4: Prefix Sum Monotonic Deque',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D] opacity-60',
        name: 'Shortest Subarray with Sum at Least K',
        diff: 'Hard',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #862',
        intuition: 'Monotonic increasing deque of prefix sum indices: pop front when prefix[i] - prefix[front] >= k.',
        status: 'Prerequisite Required',
        statusColor: 'text-[#8B949E]',
        actionText: 'Locked Barrier',
      },
    ],
  },
  math: {
    title: 'Math & Number Theory Ladder',
    desc: 'Core Invariant: Prime sieving (Eratosthenes), Euclidean GCD & Bezout identity, modular exponentiation, and combinatorial counting.',
    elo: '1,750 Elo • 88% AC',
    progress: '2 / 4 Mastered',
    steps: [
      {
        level: 'Level 1: Prime Sieve Invariant',
        badgeColor: 'text-white',
        dotColor: 'bg-white',
        borderClass: 'border-white/30',
        name: 'Count Primes',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #204',
        intuition: 'Sieve of Eratosthenes: mark composite multiples of primes up to sqrt(n) in O(N log log N).',
        status: 'Mastered',
        statusColor: 'text-white',
        actionText: 'Review Notes ->',
      },
      {
        level: 'Level 2: Euclidean GCD & Bezout',
        badgeColor: 'text-[#FF7A00]',
        dotColor: 'bg-[#FF7A00]',
        borderClass: 'border-[#FF7A00]/50',
        name: 'Water and Jug Problem',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #365',
        intuition: 'Bezout identity: target can be measured if and only if target <= x + y and target is divisible by gcd(x, y).',
        status: 'Ready to Solve',
        statusColor: 'text-[#FF7A00] font-bold',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 3: Modular Exponentiation Recursion',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D]',
        name: 'Super Pow',
        diff: 'Medium',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #372',
        intuition: 'a^[b1,b2,b3] = (a^[b1,b2])^10 * a^b3 mod 1337 evaluated via recursion.',
        status: 'Ready to Solve',
        statusColor: 'text-[#8B949E]',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 4: Place Value Digit Counting',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D] opacity-60',
        name: 'Number of Digit One',
        diff: 'Hard',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #233',
        intuition: 'Count occurrences of digit 1 at each place value (units, tens, hundreds) via high/curr/low digit arithmetic.',
        status: 'Prerequisite Required',
        statusColor: 'text-[#8B949E]',
        actionText: 'Locked Barrier',
      },
    ],
  },
  geometry: {
    title: 'Computational Geometry & Vectors Ladder',
    desc: 'Core Invariant: Normalized slope rational hashing, 2D vector cross product orientation, and Monotone Chain convex hull.',
    elo: '1,940 Elo • 73% AC',
    progress: '1 / 4 Mastered',
    steps: [
      {
        level: 'Level 1: Coordinate Distance Invariant',
        badgeColor: 'text-white',
        dotColor: 'bg-white',
        borderClass: 'border-white/30',
        name: 'Valid Square',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #593',
        intuition: 'Compute all 6 pairwise distances; square requires 4 equal sides and 2 equal diagonals > 0.',
        status: 'Mastered',
        statusColor: 'text-white',
        actionText: 'Review Notes ->',
      },
      {
        level: 'Level 2: Collinear Slope Rational Hash',
        badgeColor: 'text-[#FF7A00]',
        dotColor: 'bg-[#FF7A00]',
        borderClass: 'border-[#FF7A00]/50',
        name: 'Max Points on a Line',
        diff: 'Hard',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #149',
        intuition: 'For each anchor point, compute normalized rational slope dy/dx using gcd into hash map to prevent floating inaccuracy.',
        status: 'Ready to Solve',
        statusColor: 'text-[#FF7A00] font-bold',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 3: Diagonal Pair Hash Lookup',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D]',
        name: 'Minimum Area Rectangle',
        diff: 'Medium',
        diffClass: 'bg-[#FF7A00]/10 text-[#FF7A00] border border-[#FF7A00]/30',
        lc: 'LC #939',
        intuition: 'Iterate diagonal pairs (x1, y1) and (x2, y2); check if points (x1, y2) and (x2, y1) exist in hash set.',
        status: 'Ready to Solve',
        statusColor: 'text-[#8B949E]',
        actionText: 'Solve Problem ->',
      },
      {
        level: 'Level 4: Monotone Chain Convex Hull',
        badgeColor: 'text-[#8B949E]',
        dotColor: 'bg-[#30363D]',
        borderClass: 'border-[#21262D] opacity-60',
        name: 'Erect the Fence',
        diff: 'Hard',
        diffClass: 'bg-[#161B22] text-[#8B949E] border border-[#21262D]',
        lc: 'LC #587',
        intuition: 'Sort points, construct lower and upper hulls using 2D cross-product orientation test (clockwise vs counter-clockwise).',
        status: 'Prerequisite Required',
        statusColor: 'text-[#8B949E]',
        actionText: 'Locked Barrier',
      },
    ],
  },
`;

// Insert additionalCatalogs before the closing bracket of TOPIC_CATALOG
const catalogClosePattern = /design: \{[\s\S]*?\n    \],\n  \},\n\};/;
const match = content.match(catalogClosePattern);
if (!match) {
  console.error("Could not find design block in TOPIC_CATALOG!");
  process.exit(1);
}

const designBlock = match[0].replace(/\n\};$/, additionalCatalogs + '\n};');
content = content.replace(match[0], designBlock);

// 3. Add all missing aliases
const newAliases = `
// Aliases
TOPIC_CATALOG['sliding-window'] = TOPIC_CATALOG.window;
TOPIC_CATALOG['dynamic-programming'] = TOPIC_CATALOG.dp;
TOPIC_CATALOG['monotonic-stack'] = TOPIC_CATALOG.monostack;
TOPIC_CATALOG['binary-search'] = TOPIC_CATALOG.binsearch;
TOPIC_CATALOG['heap-priority-queue'] = TOPIC_CATALOG.heaps;
TOPIC_CATALOG['heap'] = TOPIC_CATALOG.heaps;
TOPIC_CATALOG['graph'] = TOPIC_CATALOG.graphs;
TOPIC_CATALOG['tree'] = TOPIC_CATALOG.trees;
TOPIC_CATALOG['binary-tree'] = TOPIC_CATALOG.trees;
TOPIC_CATALOG['binarytree'] = TOPIC_CATALOG.trees;
TOPIC_CATALOG['twopointers'] = TOPIC_CATALOG['two-pointers'];
TOPIC_CATALOG['prefixsum'] = TOPIC_CATALOG['prefix-sum'];
TOPIC_CATALOG['linkedlist'] = TOPIC_CATALOG['linked-list'];
TOPIC_CATALOG['dsu'] = TOPIC_CATALOG['union-find'];
TOPIC_CATALOG['unionfind'] = TOPIC_CATALOG['union-find'];
TOPIC_CATALOG['bitmanipulation'] = TOPIC_CATALOG['bit-manipulation'];
TOPIC_CATALOG['tries'] = TOPIC_CATALOG.trie;
TOPIC_CATALOG['intervals'] = TOPIC_CATALOG.greedy;
TOPIC_CATALOG['string'] = TOPIC_CATALOG.strings;
TOPIC_CATALOG['kmp'] = TOPIC_CATALOG.strings;
TOPIC_CATALOG['segment-tree'] = TOPIC_CATALOG['fenwick-tree'];
TOPIC_CATALOG['binary-indexed-tree'] = TOPIC_CATALOG['fenwick-tree'];
TOPIC_CATALOG['sweepline'] = TOPIC_CATALOG['sweep-line'];
TOPIC_CATALOG['queue'] = TOPIC_CATALOG['monotonic-queue'];
TOPIC_CATALOG['deque'] = TOPIC_CATALOG['monotonic-queue'];
TOPIC_CATALOG['number-theory'] = TOPIC_CATALOG.math;
`;

// Replace existing aliases block
content = content.replace(/\/\/ Aliases[\s\S]*?TOPIC_CATALOG\['intervals'\] = TOPIC_CATALOG\.greedy;\n/, newAliases);

// 4. Update topicsList to 24 topics
const updatedTopicsList = `  const topicsList = [
    { key: 'sliding-window', label: 'Sliding Window' },
    { key: 'two-pointers', label: 'Two Pointers' },
    { key: 'prefix-sum', label: 'Prefix Sum' },
    { key: 'linked-list', label: 'Linked List' },
    { key: 'dynamic-programming', label: 'Dynamic Programming' },
    { key: 'monotonic-stack', label: 'Monotonic Stack', isDeficit: true },
    { key: 'binary-search', label: 'Binary Search' },
    { key: 'trees', label: 'Binary Trees & BST' },
    { key: 'graphs', label: 'Graph Theory' },
    { key: 'heaps', label: 'Heaps & Hashes' },
    { key: 'backtracking', label: 'Backtracking' },
    { key: 'trie', label: 'Trie (Prefix Trees)' },
    { key: 'bit-manipulation', label: 'Bit Manipulation' },
    { key: 'union-find', label: 'Union-Find (DSU)' },
    { key: 'greedy', label: 'Greedy & Intervals' },
    { key: 'design', label: 'Data Structure Design' },
    { key: 'strings', label: 'Strings & KMP' },
    { key: 'recursion', label: 'Recursion & D&C' },
    { key: 'sorting', label: 'Sorting & Partitions' },
    { key: 'fenwick-tree', label: 'Segment & Fenwick Tree' },
    { key: 'sweep-line', label: 'Sweep Line' },
    { key: 'monotonic-queue', label: 'Monotonic Queue' },
    { key: 'math', label: 'Math & Number Theory' },
    { key: 'geometry', label: 'Geometry' },
  ];`;

content = content.replace(/const topicsList = \[[\s\S]*?\];/, updatedTopicsList.trim());

// 5. Update header badge: 24 TREES
content = content.replace('16 TREES • 35 MASTER TOPICS • 14 MAANG', '24 TREES • 35 MASTER TOPICS • 14 MAANG');
content = content.replace('Pattern Ladders (16 Trees)', 'Pattern Ladders (24 Trees)');

// 6. Embed TopicSubtopicsView right after RoadmapTree
const treeEmbed = `<RoadmapTree data={roadmapData} isProblemSolved={isProblemSolved} />`;
const subtopicsEmbed = `<RoadmapTree data={roadmapData} isProblemSolved={isProblemSolved} />

          {/* DSA Problems & Subtopics Explorer for Active Topic */}
          <TopicSubtopicsView 
            topicKey={activeTopic}
            topicTitle={data.title}
            onSwitchToMasterDsa={() => {
              setViewCategory('sheets');
              setSelectedSheetKey('master-dsa');
              navigate('/paths/master-dsa');
            }}
          />`;

if (content.includes(treeEmbed) && !content.includes('<TopicSubtopicsView')) {
  content = content.replace(treeEmbed, subtopicsEmbed);
}

fs.writeFileSync(filePath, content, 'utf8');
console.log("Successfully updated RoadmapsPage.jsx with all 24 topics, catalog ladders, aliases, and TopicSubtopicsView!");
